### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by a-kong** [jw327/dsci-310-group-01#44]
### General 
- formatting could be cleaned up in some files (remove empty spaces, skip lines between some sections)
- small typo in `test-create_boxplot.R`
- be consistent in the error messages (do you want to use backticks to indicate the function? some error messages have them, but some don't)

### Tests are written for each function, and work expected
- [x] incorrect file path
- [x] do not need to source helper files in the test files

### Test Suite Quality
- [x] functions require more thorough testing

### Dependencies
- question: why do you use R libraries from `conda-forge` (stated in your `README`) when you're installing them through R? 

### GitHub Issue Milestones
- [x] missing use of milestones

### Analysis can be run reproducibly using documentation provided in the README
- [x] dependencies in `README` do not match `Dockerfile`
