### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by a-kong** [jw327/dsci-310-group-01#73]
### Dependencies have been updated (so it include the test libraries)
- [x] missing `ggplotify` dependency
<img width="829" alt="image" src="https://user-images.githubusercontent.com/25716596/229851332-ae1ee295-f666-469b-b6d4-5d6f4483a05e.png">

### Analysis can be run reproducibly using documentation provided in the README
- [x] running `docker build` command fails (pls do not ask people to do this)
- [x] cannot reproduce in Docker container
	- `tidyverse` is not installed correctly
<img width="845" alt="image" src="https://user-images.githubusercontent.com/25716596/229851384-d6b77d70-dc31-4cbf-b739-31e5594a2837.png">

- [x] should be https://localhost:8787, not just `localhost:8787`
- [x] `Makefile` fails in Docker container and through Makefile instructions (due to missing dependencies)

### Address Feedback from Milestone 1 and 2
- marks have been updated on Canvas
- if you have any questions, please let me know!
